services:
  micro-spark:
    container_name: micro-spark
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
